# Generated by Django 6.1 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
