# Generated by Django 6.1 on 2026-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['featured_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='featured_order',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
