# Generated by Django 6.1 on 2026-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_remove_productimage_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use this image as the main product image.'),
        ),
    ]
